#!/bin/sh -e

git submodule update --init
if [ ! -d .tup ] ; then tup init; fi
tup upd

rsync \
	-f "- *.scss" \
	-f "- static/css/compass" \
	-f "- Tupfile" \
  -f "- *.rb" \
	-f "- *.swp" \
	-f "- *.swo" \
	-f "- *.coffee" \
	-f "- .gitignore" \
	--delete --delete-excluded \
	-Lavz -e ssh web/ brad@braddunbar.net:/var/sites/braddunbar

ssh -t braddunbar.net "sudo chown -R brad:www-data /var/sites/braddunbar"
ssh -t braddunbar.net "sudo chmod 644 \$(find /var/sites/braddunbar -type f)"
