#!/bin/sh -e

v="$(sass -v | sed 's/[^0-9.]//g')"
if [ -z "$(semver -v "$v" -r ">=3.1")" ]
then
	echo "sass@>=3.1 required"
	false
fi

sass="sass -C --scss --trace"

while getopts ":mr:" opt; do
	case $opt in
		m) sass="$sass -t compressed";;
		r) sass="$sass -r $OPTARG";;
		\?) echo "invalid option: -$OPTARG"; exit;;
	esac
done
shift $((OPTIND-1))

awk 'FNR==1 && NR!=1{print "\n"}{print}' $@ | $sass
